spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: catalog_route
          uri: http://catalog-service:8083
          predicates:
            - Path=/catalog-service/**
        - id: inventory_route
          uri: http://inventory-service:8085
          predicates:
            - Path=/inventory-service/**
        - id: PRODUCTS-SERVICE
          uri: http://product-service:8086
          predicates:
            - Path=/products-service/**
management:
  endpoints:
    web:
      exposure:
        include: gateway

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://registry-service:8761/eureka}
  instance:
    preferIpAddress: true
