spring:
  application:
    name: registry-service
  management:
    endpoints:
      web:
        exposure:
          include: "health,refresh"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
    endpoint:
      health:
        probes:
          enabled: true

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
