spring:
  application:
    name: product-service
  config: # optional keyword down here makes this service can start without having available config server
    import: optional:configserver:http://root:s3cr3t@localhost:8888?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 4
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000000
      failureRateThreshold: 60
    someShared:
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 10
  instances:
    CatalogClient_findByUniqId:
      baseConfig: default
      waitDurationInOpenState: 5000
    CatalogClient_findBySku:
      baseConfig: someShared
    InventoryClient_findByUniqIds:
      baseConfig: someShared


management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
